server:
  port: 8030

spring:
  application:
    name: zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true

zuul:
  routes:
    provide: /provide/**
    sonsume: /sonsume/**