server:
  port: 8012


eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

  instance:
    prefer-ip-address: true

spring:
  datasource:
    url: jdbc:mysql://120.77.159.19:3306/mei?useUnicode=true&characterEncoding=utf8&useSSL=true
    username: mei
    password: meijiabo
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: provide
