server:
  port: 8888

eureka:
  client:
    service-uri:
      defaultZone: http://localhost:7001/eureka/
  instance:
    prefer-ip-address: true

spring:
  application:
    name: configclien1
foo: meijiabo
student:
  name: 梅加波
  age: 23
  sex: 男
